//Export backup registration definitions
backup_registration.xml  /epoc32/data/z/private/101F4CD5/backup_registration.xml
backup_registration.xml  /epoc32/release/winscw/udeb/z/private/101F4CD5/backup_registration.xml
backup_registration.xml /epoc32/release/winscw/urel/z/private/101F4CD5/backup_registration.xml

// Generic configuration interface for component cenrep settings  
// .crml implementation specifics for cenrep data
../conf/logs.confml                     APP_LAYER_CONFML(logs.confml)
../conf/logs_101F874E.crml 	        APP_LAYER_CRML(logs_101F874E.crml)
../conf/logs_102750C6.crml        	APP_LAYER_CRML(logs_102750C6.crml)


