#
# Copyright (c) 2002 Nokia Corporation and/or its subsidiary(-ies).
# All rights reserved.
# This component and the accompanying materials are made available
# under the terms of the License "Eclipse Public License v1.0"
# which accompanies this distribution, and is available
# at the URL "http://www.eclipse.org/legal/epl-v10.html".
#
# Initial Contributors:
# Nokia Corporation - initial contribution.
#
# Contributors:
#
# Description: 
#    String table for the parsing the XML inport file
#    containing predefined contacts.
#
fstringtable PdcStringTable
EContact    Contact
EFirstName  FirstName
ELastName   LastName
ECompany    Company
EJob        Job
EGeneral    General
EMobile     Mobile
EVideoNo    VideoNo
EFax        Fax
EEmail      Email
EWvUserId   WvUserId
EURL        URL
ETopContact  TopContact
ESpeeddialNo	SpeeddialNo
ESpeeddialNoAssign	SpeeddialNoAssign